const {parseDuration,parseTime,formatTime,calculate}=Timeline;
let nodes=[],durations=[],serial=0;
const el=id=>document.getElementById(id);
function node(name,type,manualTime=null){return {id:String(++serial),name,type,manualTime,calculatedTime:null}}
function reset(){nodes=[node('九龙塘','departure','09:00'),node('福田站','arrival'),node('商场','arrival'),node('午餐 / 休息','departure')];durations=['45min','30min','1h20min'];render()}
function input(className,label,value){const x=document.createElement('input');x.className=className;x.setAttribute('aria-label',label);x.value=value;return x}
function render(){el('timeline').replaceChildren();nodes.forEach((n,i)=>{const box=document.createElement('div');box.className='node';const top=document.createElement('div');top.className='node-top';const time=input('time',`第 ${i+1} 个节点的已知时间，格式 HH:MM`,'');time.placeholder='--:--';time.maxLength=5;time.title='输入已知时间；清空后恢复自动推算';time.addEventListener('change',()=>{n.manualTime=time.value.trim()||null;refresh()});const source=document.createElement('div');source.className='source';const type=document.createElement('select');type.className='type';type.setAttribute('aria-label',`第 ${i+1} 个节点类型`);['departure','arrival'].forEach((value,j)=>{const option=new Option(j?'到达':'出发',value);type.add(option)});type.value=n.type;type.onchange=()=>n.type=type.value;top.append(time,source,type);const dot=document.createElement('div');dot.className='dot';const name=input('name',`第 ${i+1} 个节点名称`,n.name);name.maxLength=40;name.oninput=()=>n.name=name.value;const bottom=document.createElement('div');bottom.className='node-bottom';const remove=document.createElement('button');remove.className='remove';remove.textContent='移除节点';remove.disabled=nodes.length===1;remove.onclick=()=>{if(i>0&&i<nodes.length-1){const a=parseDuration(durations[i-1]),b=parseDuration(durations[i]);durations.splice(i-1,2,a!==null&&b!==null?`${a+b}min`:'')}else durations.splice(i===0?0:i-1,1);nodes.splice(i,1);render()};bottom.append(remove);box.append(top,dot,name,bottom);el('timeline').append(box);if(i<nodes.length-1){const seg=document.createElement('div');seg.className='segment';const duration=input('duration',`第 ${i+1} 段耗时`,durations[i]);duration.placeholder='如 45min';duration.oninput=()=>{durations[i]=duration.value;refresh()};const hint=document.createElement('small');hint.textContent='途中耗时';seg.append(duration,hint);el('timeline').append(seg)}});refresh()}
function refresh(){const result=calculate(nodes,durations);let warnings=[...result.errors];document.querySelectorAll('.node').forEach((box,i)=>{const n=nodes[i],t=result.times[i],invalid=n.manualTime!==null&&parseTime(n.manualTime)===null;n.calculatedTime=n.manualTime?null:formatTime(t)||null;const field=box.querySelector('.time');field.value=n.manualTime||formatTime(t);field.className='time'+(n.manualTime?' manual':'')+(invalid?' invalid':'');field.setAttribute('aria-invalid',String(invalid));const source=box.querySelector('.source');source.className='source'+(n.manualTime?' manual-source':'');source.textContent=invalid?'请输入 HH:MM':n.manualTime?'已知时间 · 可清空':t===null?'等待已知时间':t<0?'前一天 · 超出单日':t>=1440?'次日 · 超出单日':'自动推算';if(invalid)warnings.push(`第 ${i+1} 个节点请输入有效时间，如 09:45`)});document.querySelectorAll('.duration').forEach((field,i)=>{const invalid=parseDuration(durations[i])===null;field.classList.toggle('invalid',invalid);field.setAttribute('aria-invalid',String(invalid));if(invalid)warnings.push(`第 ${i+1} 段请填写小于 24 小时的耗时，如 1h20min`)});if(result.times.some(t=>t!==null&&(t<0||t>=1440)))warnings.push('行程超出当天，请调整已知时间或耗时');if(!nodes.some(n=>parseTime(n.manualTime)!==null))warnings.push('请在任意节点输入一个已知时间，开始自动推算');el('status').className='status'+(warnings.length?' warning':'');el('status').textContent=warnings.length?'ⓘ '+warnings.join('；'):'✓ 时间线已同步 · 修改任意一段耗时，前后时间会自动更新。';el('count').textContent=`节点数量：${nodes.length} / 20`;el('add').disabled=nodes.length>=20;const display=t=>t===null?'—':(t<0?'前日 ':t>=1440?'次日 ':'')+formatTime(t);el('start').textContent=display(result.times[0]);el('end').textContent=display(result.times.at(-1));const total=durations.map(parseDuration);const mins=total.reduce((a,b)=>a+(b||0),0);el('total').textContent=total.includes(null)?'待完善':`${Math.floor(mins/60)?Math.floor(mins/60)+'h ':''}${mins%60}min`}
el('add').onclick=()=>{if(nodes.length>=20)return;nodes.push(node('新地点','arrival'));durations.push('30min');render();const area=document.querySelector('.timeline-scroll');area.scrollTo({left:area.scrollWidth,behavior:'smooth'});document.querySelector('.node:last-child .name').focus({preventScroll:true})};el('reset').onclick=reset;reset();
